/*
 * BootNotificationResponse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package io.opencpms.ocpp16.protocol.message

import io.opencpms.ocpp16.protocol.Ocpp16OutgoingMessage
import java.time.OffsetDateTime

data class BootNotificationResponse(
    val status: Status,
    val currentTime: OffsetDateTime,
    val interval: Long
) : Ocpp16OutgoingMessage {

    enum class Status {
        Accepted,
        Pending,
        Rejected
    }

}
